name: GhostBlockLib
version: '${project.version}'
main: me.nonetaken.ghostblocklib.GhostBlockLib
authors: [ NoneTaken ]
description: A library to handle GhostBlock regions
depend: [ packetevents ]
commands:
  ignoreghostblocks:
    description: "When enabled, you will not be sent GhostBlocks"
    permission: "ghostblocklib.ignoreghostblocks"
  testghostblocks: